# exclude-use-default option in enabled by default https://golangci-lint.run/usage/configuration/ which means
# some rules won't be reported by golangci-lint but will be reported by individual binaries
linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - exhaustive
    # binary https://staticcheck.io/ != staticcheck here
    # staticcheck here refers to a set of rules that golangci-lint executes
    # while in staticcheck.io, staticcheck is binary that executes a set of rules
    # This explains it better: https://github.com/golangci/golangci-lint/issues/3495
    - staticcheck
    - stylecheck
    - gosimple
    - unused
linters-settings:
  errcheck:
    check-blank: true
  exhaustive:
    check:
      - switch
      - map
    default-signifies-exhaustive: true
  stylecheck:
    # default taken from https://staticcheck.io/docs/configuration/options/#checks
    checks:
      ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]
