# default option list at https://dystroy.org/bacon/config/

default_job = "clippy"

[jobs.clippy]
command = [
    "cargo", "clippy",
    # commenting until https://github.com/Canop/nvim-bacon/issues/3 is resolved
    # "--quiet",
    "--all-targets",
    "--color", "always",
]
need_stdout = false

[keybindings]
k = "scroll-lines(-1)"
j = "scroll-lines(1)"

